from odoo import http
from odoo.http import request
from odoo.exceptions import ValidationError

import base64


class ITSMWebsite(http.Controller):

    # =====================================================
    # Support Form Page
    # =====================================================
    @http.route('/support', type='http', auth='user', website=True)
    def support_form(self, **kw):
        teams = request.env['itsm.team'].sudo().search([])

        return request.render(
            'itsm_support.support_form_template',
            {'teams': teams}
        )


    # =====================================================
    # Create Ticket
    # =====================================================
    @http.route(
        '/support/create',
        type='http',
        auth='user',
        website=True,
        methods=['POST'],
        csrf=True
    )
    def support_create(self, **post):

        # -------------------------
        # Read form values
        # -------------------------
        name = post.get('name')
        email = post.get('email')
        subject = post.get('subject') or 'No Title'
        description = post.get('description')
        team_id = post.get('team_id')

        # -------------------------
        # Find or create partner
        # -------------------------
        partner = request.env['res.partner'].sudo().search(
            [('email', '=', email)], limit=1
        )

        if not partner:
            partner = request.env['res.partner'].sudo().create({
                'name': name,
                'email': email,
            })

        # -------------------------
        # Create ticket
        # (name/number generated by sequence automatically)
        # -------------------------
        ticket = request.env['itsm.ticket'].sudo().create({
            'subject': subject,
            'description': description,
            'partner_id': request.env.user.partner_id.id,
            'team_id': int(team_id) if team_id else False,
        })

        # -------------------------
        # Attachments (screenshots only)
        # -------------------------
        files = request.httprequest.files.getlist('attachment')

        ALLOWED_TYPES = {
            'image/png',
            'image/jpeg',
            'image/jpg',
            'image/webp',
            'image/gif',
        }

        MAX_SIZE = 5 * 1024 * 1024  # 5MB

        for file in files:

            if not file or not file.filename:
                continue

            # Validate type
            if file.mimetype not in ALLOWED_TYPES:
                raise ValidationError(
                    "Only screenshots are allowed (PNG/JPG/GIF/WEBP)."
                )

            data = file.read()

            # Validate size
            if len(data) > MAX_SIZE:
                raise ValidationError(
                    "Each screenshot must be smaller than 5MB."
                )

            request.env['ir.attachment'].sudo().create({
                'name': file.filename,
                'datas': base64.b64encode(data),
                'res_model': 'itsm.ticket',
                'res_id': ticket.id,
                'mimetype': file.mimetype,
            })

        # -------------------------
        # Redirect to thank you
        # -------------------------
        return request.redirect('/support/thanks/%s' % ticket.id)


    # =====================================================
    # Thank you page
    # =====================================================
    @http.route(
        '/support/thanks/<int:ticket_id>',
        type='http',
        auth='user',
        website=True
    )
    def support_thanks(self, ticket_id=None, **kw):

        ticket = request.env['itsm.ticket'].sudo().browse(ticket_id)

        return request.render(
            'itsm_support.support_thanks_template',
            {'ticket': ticket}
        )
